# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: BSD-2-Clause

[package]
name = "install-mimic"
version = "0.4.2"
edition = "2024"
rust-version = "1.85"
authors = ["Peter Pentchev <roam@ringlet.net>"]
description = "Overwrite files preserving the destination's ownership and access mode"
readme = "README.md"
license = "BSD-2-Clause"
repository = "https://gitlab.com/ppentchev/install-mimic"
categories = ["command-line-utilities", "filesystem"]
keywords = ["install", "file", "preserve"]

[[bin]]
name = "install-mimic"
path = "install-mimic.rs"

[dependencies]
eyre = "0.6.12"
clap = "4.0.8"
clap_derive = "4.0.8"
shell-words = "1.1"

[dev-dependencies]
camino = "1.1.9"
