[package]
name = "install-mimic"
version = "0.4.0"
edition = "2018"
authors = ["Peter Pentchev <roam@ringlet.net>"]
 
[[bin]]
name = "install-mimic"
path = "install-mimic.rs"

[dependencies]
expect-exit = "0.3.1"
getopts = "0.2"
